<?php
/**
 * CommonModelsCvssV30CveCvssDataModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Msn\Apis\FastCVE\Model;

use \ArrayAccess;
use \Msn\Apis\FastCVE\ObjectSerializer;

/**
 * CommonModelsCvssV30CveCvssDataModel Class Doc Comment
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CommonModelsCvssV30CveCvssDataModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'common__models__cvss_v30__CveCvssDataModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'version' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30Version',
        'vector_string' => 'string',
        'attack_vector' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackVectorType',
        'attack_complexity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackComplexityType',
        'privileges_required' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30PrivilegesRequiredType',
        'user_interaction' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30UserInteractionType',
        'scope' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ScopeType',
        'confidentiality_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType',
        'integrity_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType',
        'availability_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType',
        'base_score' => 'float',
        'base_severity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType',
        'exploit_code_maturity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ExploitCodeMaturityType',
        'remediation_level' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30RemediationLevelType',
        'report_confidence' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ConfidenceType',
        'temporal_score' => 'float',
        'temporal_severity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType',
        'confidentiality_requirement' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType',
        'integrity_requirement' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType',
        'availability_requirement' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType',
        'modified_attack_vector' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackVectorType',
        'modified_attack_complexity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackComplexityType',
        'modified_privileges_required' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedPrivilegesRequiredType',
        'modified_user_interaction' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedUserInteractionType',
        'modified_scope' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedScopeType',
        'modified_confidentiality_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType',
        'modified_integrity_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType',
        'modified_availability_impact' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType',
        'environmental_score' => 'float',
        'environmental_severity' => '\Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'version' => null,
        'vector_string' => null,
        'attack_vector' => null,
        'attack_complexity' => null,
        'privileges_required' => null,
        'user_interaction' => null,
        'scope' => null,
        'confidentiality_impact' => null,
        'integrity_impact' => null,
        'availability_impact' => null,
        'base_score' => null,
        'base_severity' => null,
        'exploit_code_maturity' => null,
        'remediation_level' => null,
        'report_confidence' => null,
        'temporal_score' => null,
        'temporal_severity' => null,
        'confidentiality_requirement' => null,
        'integrity_requirement' => null,
        'availability_requirement' => null,
        'modified_attack_vector' => null,
        'modified_attack_complexity' => null,
        'modified_privileges_required' => null,
        'modified_user_interaction' => null,
        'modified_scope' => null,
        'modified_confidentiality_impact' => null,
        'modified_integrity_impact' => null,
        'modified_availability_impact' => null,
        'environmental_score' => null,
        'environmental_severity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'version' => false,
		'vector_string' => false,
		'attack_vector' => false,
		'attack_complexity' => false,
		'privileges_required' => false,
		'user_interaction' => false,
		'scope' => false,
		'confidentiality_impact' => false,
		'integrity_impact' => false,
		'availability_impact' => false,
		'base_score' => false,
		'base_severity' => false,
		'exploit_code_maturity' => false,
		'remediation_level' => false,
		'report_confidence' => false,
		'temporal_score' => false,
		'temporal_severity' => false,
		'confidentiality_requirement' => false,
		'integrity_requirement' => false,
		'availability_requirement' => false,
		'modified_attack_vector' => false,
		'modified_attack_complexity' => false,
		'modified_privileges_required' => false,
		'modified_user_interaction' => false,
		'modified_scope' => false,
		'modified_confidentiality_impact' => false,
		'modified_integrity_impact' => false,
		'modified_availability_impact' => false,
		'environmental_score' => false,
		'environmental_severity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'version' => 'version',
        'vector_string' => 'vectorString',
        'attack_vector' => 'attackVector',
        'attack_complexity' => 'attackComplexity',
        'privileges_required' => 'privilegesRequired',
        'user_interaction' => 'userInteraction',
        'scope' => 'scope',
        'confidentiality_impact' => 'confidentialityImpact',
        'integrity_impact' => 'integrityImpact',
        'availability_impact' => 'availabilityImpact',
        'base_score' => 'baseScore',
        'base_severity' => 'baseSeverity',
        'exploit_code_maturity' => 'exploitCodeMaturity',
        'remediation_level' => 'remediationLevel',
        'report_confidence' => 'reportConfidence',
        'temporal_score' => 'temporalScore',
        'temporal_severity' => 'temporalSeverity',
        'confidentiality_requirement' => 'confidentialityRequirement',
        'integrity_requirement' => 'integrityRequirement',
        'availability_requirement' => 'availabilityRequirement',
        'modified_attack_vector' => 'modifiedAttackVector',
        'modified_attack_complexity' => 'modifiedAttackComplexity',
        'modified_privileges_required' => 'modifiedPrivilegesRequired',
        'modified_user_interaction' => 'modifiedUserInteraction',
        'modified_scope' => 'modifiedScope',
        'modified_confidentiality_impact' => 'modifiedConfidentialityImpact',
        'modified_integrity_impact' => 'modifiedIntegrityImpact',
        'modified_availability_impact' => 'modifiedAvailabilityImpact',
        'environmental_score' => 'environmentalScore',
        'environmental_severity' => 'environmentalSeverity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'version' => 'setVersion',
        'vector_string' => 'setVectorString',
        'attack_vector' => 'setAttackVector',
        'attack_complexity' => 'setAttackComplexity',
        'privileges_required' => 'setPrivilegesRequired',
        'user_interaction' => 'setUserInteraction',
        'scope' => 'setScope',
        'confidentiality_impact' => 'setConfidentialityImpact',
        'integrity_impact' => 'setIntegrityImpact',
        'availability_impact' => 'setAvailabilityImpact',
        'base_score' => 'setBaseScore',
        'base_severity' => 'setBaseSeverity',
        'exploit_code_maturity' => 'setExploitCodeMaturity',
        'remediation_level' => 'setRemediationLevel',
        'report_confidence' => 'setReportConfidence',
        'temporal_score' => 'setTemporalScore',
        'temporal_severity' => 'setTemporalSeverity',
        'confidentiality_requirement' => 'setConfidentialityRequirement',
        'integrity_requirement' => 'setIntegrityRequirement',
        'availability_requirement' => 'setAvailabilityRequirement',
        'modified_attack_vector' => 'setModifiedAttackVector',
        'modified_attack_complexity' => 'setModifiedAttackComplexity',
        'modified_privileges_required' => 'setModifiedPrivilegesRequired',
        'modified_user_interaction' => 'setModifiedUserInteraction',
        'modified_scope' => 'setModifiedScope',
        'modified_confidentiality_impact' => 'setModifiedConfidentialityImpact',
        'modified_integrity_impact' => 'setModifiedIntegrityImpact',
        'modified_availability_impact' => 'setModifiedAvailabilityImpact',
        'environmental_score' => 'setEnvironmentalScore',
        'environmental_severity' => 'setEnvironmentalSeverity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'version' => 'getVersion',
        'vector_string' => 'getVectorString',
        'attack_vector' => 'getAttackVector',
        'attack_complexity' => 'getAttackComplexity',
        'privileges_required' => 'getPrivilegesRequired',
        'user_interaction' => 'getUserInteraction',
        'scope' => 'getScope',
        'confidentiality_impact' => 'getConfidentialityImpact',
        'integrity_impact' => 'getIntegrityImpact',
        'availability_impact' => 'getAvailabilityImpact',
        'base_score' => 'getBaseScore',
        'base_severity' => 'getBaseSeverity',
        'exploit_code_maturity' => 'getExploitCodeMaturity',
        'remediation_level' => 'getRemediationLevel',
        'report_confidence' => 'getReportConfidence',
        'temporal_score' => 'getTemporalScore',
        'temporal_severity' => 'getTemporalSeverity',
        'confidentiality_requirement' => 'getConfidentialityRequirement',
        'integrity_requirement' => 'getIntegrityRequirement',
        'availability_requirement' => 'getAvailabilityRequirement',
        'modified_attack_vector' => 'getModifiedAttackVector',
        'modified_attack_complexity' => 'getModifiedAttackComplexity',
        'modified_privileges_required' => 'getModifiedPrivilegesRequired',
        'modified_user_interaction' => 'getModifiedUserInteraction',
        'modified_scope' => 'getModifiedScope',
        'modified_confidentiality_impact' => 'getModifiedConfidentialityImpact',
        'modified_integrity_impact' => 'getModifiedIntegrityImpact',
        'modified_availability_impact' => 'getModifiedAvailabilityImpact',
        'environmental_score' => 'getEnvironmentalScore',
        'environmental_severity' => 'getEnvironmentalSeverity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('vector_string', $data ?? [], null);
        $this->setIfExists('attack_vector', $data ?? [], null);
        $this->setIfExists('attack_complexity', $data ?? [], null);
        $this->setIfExists('privileges_required', $data ?? [], null);
        $this->setIfExists('user_interaction', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('confidentiality_impact', $data ?? [], null);
        $this->setIfExists('integrity_impact', $data ?? [], null);
        $this->setIfExists('availability_impact', $data ?? [], null);
        $this->setIfExists('base_score', $data ?? [], null);
        $this->setIfExists('base_severity', $data ?? [], null);
        $this->setIfExists('exploit_code_maturity', $data ?? [], null);
        $this->setIfExists('remediation_level', $data ?? [], null);
        $this->setIfExists('report_confidence', $data ?? [], null);
        $this->setIfExists('temporal_score', $data ?? [], null);
        $this->setIfExists('temporal_severity', $data ?? [], null);
        $this->setIfExists('confidentiality_requirement', $data ?? [], null);
        $this->setIfExists('integrity_requirement', $data ?? [], null);
        $this->setIfExists('availability_requirement', $data ?? [], null);
        $this->setIfExists('modified_attack_vector', $data ?? [], null);
        $this->setIfExists('modified_attack_complexity', $data ?? [], null);
        $this->setIfExists('modified_privileges_required', $data ?? [], null);
        $this->setIfExists('modified_user_interaction', $data ?? [], null);
        $this->setIfExists('modified_scope', $data ?? [], null);
        $this->setIfExists('modified_confidentiality_impact', $data ?? [], null);
        $this->setIfExists('modified_integrity_impact', $data ?? [], null);
        $this->setIfExists('modified_availability_impact', $data ?? [], null);
        $this->setIfExists('environmental_score', $data ?? [], null);
        $this->setIfExists('environmental_severity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['vector_string'] === null) {
            $invalidProperties[] = "'vector_string' can't be null";
        }
        if (!preg_match("/^CVSS:3[.]0\/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])\/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$/", $this->container['vector_string'])) {
            $invalidProperties[] = "invalid value for 'vector_string', must be conform to the pattern /^CVSS:3[.]0\/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])\/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$/.";
        }

        if ($this->container['base_score'] === null) {
            $invalidProperties[] = "'base_score' can't be null";
        }
        if (($this->container['base_score'] > 10.0)) {
            $invalidProperties[] = "invalid value for 'base_score', must be smaller than or equal to 10.0.";
        }

        if (($this->container['base_score'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'base_score', must be bigger than or equal to 0.0.";
        }

        if ($this->container['base_severity'] === null) {
            $invalidProperties[] = "'base_severity' can't be null";
        }
        if (!is_null($this->container['temporal_score']) && ($this->container['temporal_score'] > 10.0)) {
            $invalidProperties[] = "invalid value for 'temporal_score', must be smaller than or equal to 10.0.";
        }

        if (!is_null($this->container['temporal_score']) && ($this->container['temporal_score'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'temporal_score', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['environmental_score']) && ($this->container['environmental_score'] > 10.0)) {
            $invalidProperties[] = "invalid value for 'environmental_score', must be smaller than or equal to 10.0.";
        }

        if (!is_null($this->container['environmental_score']) && ($this->container['environmental_score'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'environmental_score', must be bigger than or equal to 0.0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets version
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30Version
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30Version $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets vector_string
     *
     * @return string
     */
    public function getVectorString()
    {
        return $this->container['vector_string'];
    }

    /**
     * Sets vector_string
     *
     * @param string $vector_string vector_string
     *
     * @return self
     */
    public function setVectorString($vector_string)
    {
        if (is_null($vector_string)) {
            throw new \InvalidArgumentException('non-nullable vector_string cannot be null');
        }

        if ((!preg_match("/^CVSS:3[.]0\/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])\/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$/", ObjectSerializer::toString($vector_string)))) {
            throw new \InvalidArgumentException("invalid value for \$vector_string when calling CommonModelsCvssV30CveCvssDataModel., must conform to the pattern /^CVSS:3[.]0\/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])\/)*(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$/.");
        }

        $this->container['vector_string'] = $vector_string;

        return $this;
    }

    /**
     * Gets attack_vector
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackVectorType|null
     */
    public function getAttackVector()
    {
        return $this->container['attack_vector'];
    }

    /**
     * Sets attack_vector
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackVectorType|null $attack_vector attack_vector
     *
     * @return self
     */
    public function setAttackVector($attack_vector)
    {
        if (is_null($attack_vector)) {
            throw new \InvalidArgumentException('non-nullable attack_vector cannot be null');
        }
        $this->container['attack_vector'] = $attack_vector;

        return $this;
    }

    /**
     * Gets attack_complexity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackComplexityType|null
     */
    public function getAttackComplexity()
    {
        return $this->container['attack_complexity'];
    }

    /**
     * Sets attack_complexity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30AttackComplexityType|null $attack_complexity attack_complexity
     *
     * @return self
     */
    public function setAttackComplexity($attack_complexity)
    {
        if (is_null($attack_complexity)) {
            throw new \InvalidArgumentException('non-nullable attack_complexity cannot be null');
        }
        $this->container['attack_complexity'] = $attack_complexity;

        return $this;
    }

    /**
     * Gets privileges_required
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30PrivilegesRequiredType|null
     */
    public function getPrivilegesRequired()
    {
        return $this->container['privileges_required'];
    }

    /**
     * Sets privileges_required
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30PrivilegesRequiredType|null $privileges_required privileges_required
     *
     * @return self
     */
    public function setPrivilegesRequired($privileges_required)
    {
        if (is_null($privileges_required)) {
            throw new \InvalidArgumentException('non-nullable privileges_required cannot be null');
        }
        $this->container['privileges_required'] = $privileges_required;

        return $this;
    }

    /**
     * Gets user_interaction
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30UserInteractionType|null
     */
    public function getUserInteraction()
    {
        return $this->container['user_interaction'];
    }

    /**
     * Sets user_interaction
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30UserInteractionType|null $user_interaction user_interaction
     *
     * @return self
     */
    public function setUserInteraction($user_interaction)
    {
        if (is_null($user_interaction)) {
            throw new \InvalidArgumentException('non-nullable user_interaction cannot be null');
        }
        $this->container['user_interaction'] = $user_interaction;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ScopeType|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ScopeType|null $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets confidentiality_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null
     */
    public function getConfidentialityImpact()
    {
        return $this->container['confidentiality_impact'];
    }

    /**
     * Sets confidentiality_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null $confidentiality_impact confidentiality_impact
     *
     * @return self
     */
    public function setConfidentialityImpact($confidentiality_impact)
    {
        if (is_null($confidentiality_impact)) {
            throw new \InvalidArgumentException('non-nullable confidentiality_impact cannot be null');
        }
        $this->container['confidentiality_impact'] = $confidentiality_impact;

        return $this;
    }

    /**
     * Gets integrity_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null
     */
    public function getIntegrityImpact()
    {
        return $this->container['integrity_impact'];
    }

    /**
     * Sets integrity_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null $integrity_impact integrity_impact
     *
     * @return self
     */
    public function setIntegrityImpact($integrity_impact)
    {
        if (is_null($integrity_impact)) {
            throw new \InvalidArgumentException('non-nullable integrity_impact cannot be null');
        }
        $this->container['integrity_impact'] = $integrity_impact;

        return $this;
    }

    /**
     * Gets availability_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null
     */
    public function getAvailabilityImpact()
    {
        return $this->container['availability_impact'];
    }

    /**
     * Sets availability_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaType|null $availability_impact availability_impact
     *
     * @return self
     */
    public function setAvailabilityImpact($availability_impact)
    {
        if (is_null($availability_impact)) {
            throw new \InvalidArgumentException('non-nullable availability_impact cannot be null');
        }
        $this->container['availability_impact'] = $availability_impact;

        return $this;
    }

    /**
     * Gets base_score
     *
     * @return float
     */
    public function getBaseScore()
    {
        return $this->container['base_score'];
    }

    /**
     * Sets base_score
     *
     * @param float $base_score base_score
     *
     * @return self
     */
    public function setBaseScore($base_score)
    {
        if (is_null($base_score)) {
            throw new \InvalidArgumentException('non-nullable base_score cannot be null');
        }

        if (($base_score > 10.0)) {
            throw new \InvalidArgumentException('invalid value for $base_score when calling CommonModelsCvssV30CveCvssDataModel., must be smaller than or equal to 10.0.');
        }
        if (($base_score < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $base_score when calling CommonModelsCvssV30CveCvssDataModel., must be bigger than or equal to 0.0.');
        }

        $this->container['base_score'] = $base_score;

        return $this;
    }

    /**
     * Gets base_severity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType
     */
    public function getBaseSeverity()
    {
        return $this->container['base_severity'];
    }

    /**
     * Sets base_severity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType $base_severity base_severity
     *
     * @return self
     */
    public function setBaseSeverity($base_severity)
    {
        if (is_null($base_severity)) {
            throw new \InvalidArgumentException('non-nullable base_severity cannot be null');
        }
        $this->container['base_severity'] = $base_severity;

        return $this;
    }

    /**
     * Gets exploit_code_maturity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ExploitCodeMaturityType|null
     */
    public function getExploitCodeMaturity()
    {
        return $this->container['exploit_code_maturity'];
    }

    /**
     * Sets exploit_code_maturity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ExploitCodeMaturityType|null $exploit_code_maturity exploit_code_maturity
     *
     * @return self
     */
    public function setExploitCodeMaturity($exploit_code_maturity)
    {
        if (is_null($exploit_code_maturity)) {
            throw new \InvalidArgumentException('non-nullable exploit_code_maturity cannot be null');
        }
        $this->container['exploit_code_maturity'] = $exploit_code_maturity;

        return $this;
    }

    /**
     * Gets remediation_level
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30RemediationLevelType|null
     */
    public function getRemediationLevel()
    {
        return $this->container['remediation_level'];
    }

    /**
     * Sets remediation_level
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30RemediationLevelType|null $remediation_level remediation_level
     *
     * @return self
     */
    public function setRemediationLevel($remediation_level)
    {
        if (is_null($remediation_level)) {
            throw new \InvalidArgumentException('non-nullable remediation_level cannot be null');
        }
        $this->container['remediation_level'] = $remediation_level;

        return $this;
    }

    /**
     * Gets report_confidence
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ConfidenceType|null
     */
    public function getReportConfidence()
    {
        return $this->container['report_confidence'];
    }

    /**
     * Sets report_confidence
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ConfidenceType|null $report_confidence report_confidence
     *
     * @return self
     */
    public function setReportConfidence($report_confidence)
    {
        if (is_null($report_confidence)) {
            throw new \InvalidArgumentException('non-nullable report_confidence cannot be null');
        }
        $this->container['report_confidence'] = $report_confidence;

        return $this;
    }

    /**
     * Gets temporal_score
     *
     * @return float|null
     */
    public function getTemporalScore()
    {
        return $this->container['temporal_score'];
    }

    /**
     * Sets temporal_score
     *
     * @param float|null $temporal_score temporal_score
     *
     * @return self
     */
    public function setTemporalScore($temporal_score)
    {
        if (is_null($temporal_score)) {
            throw new \InvalidArgumentException('non-nullable temporal_score cannot be null');
        }

        if (($temporal_score > 10.0)) {
            throw new \InvalidArgumentException('invalid value for $temporal_score when calling CommonModelsCvssV30CveCvssDataModel., must be smaller than or equal to 10.0.');
        }
        if (($temporal_score < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $temporal_score when calling CommonModelsCvssV30CveCvssDataModel., must be bigger than or equal to 0.0.');
        }

        $this->container['temporal_score'] = $temporal_score;

        return $this;
    }

    /**
     * Gets temporal_severity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType|null
     */
    public function getTemporalSeverity()
    {
        return $this->container['temporal_severity'];
    }

    /**
     * Sets temporal_severity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType|null $temporal_severity temporal_severity
     *
     * @return self
     */
    public function setTemporalSeverity($temporal_severity)
    {
        if (is_null($temporal_severity)) {
            throw new \InvalidArgumentException('non-nullable temporal_severity cannot be null');
        }
        $this->container['temporal_severity'] = $temporal_severity;

        return $this;
    }

    /**
     * Gets confidentiality_requirement
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null
     */
    public function getConfidentialityRequirement()
    {
        return $this->container['confidentiality_requirement'];
    }

    /**
     * Sets confidentiality_requirement
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null $confidentiality_requirement confidentiality_requirement
     *
     * @return self
     */
    public function setConfidentialityRequirement($confidentiality_requirement)
    {
        if (is_null($confidentiality_requirement)) {
            throw new \InvalidArgumentException('non-nullable confidentiality_requirement cannot be null');
        }
        $this->container['confidentiality_requirement'] = $confidentiality_requirement;

        return $this;
    }

    /**
     * Gets integrity_requirement
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null
     */
    public function getIntegrityRequirement()
    {
        return $this->container['integrity_requirement'];
    }

    /**
     * Sets integrity_requirement
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null $integrity_requirement integrity_requirement
     *
     * @return self
     */
    public function setIntegrityRequirement($integrity_requirement)
    {
        if (is_null($integrity_requirement)) {
            throw new \InvalidArgumentException('non-nullable integrity_requirement cannot be null');
        }
        $this->container['integrity_requirement'] = $integrity_requirement;

        return $this;
    }

    /**
     * Gets availability_requirement
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null
     */
    public function getAvailabilityRequirement()
    {
        return $this->container['availability_requirement'];
    }

    /**
     * Sets availability_requirement
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30CiaRequirementType|null $availability_requirement availability_requirement
     *
     * @return self
     */
    public function setAvailabilityRequirement($availability_requirement)
    {
        if (is_null($availability_requirement)) {
            throw new \InvalidArgumentException('non-nullable availability_requirement cannot be null');
        }
        $this->container['availability_requirement'] = $availability_requirement;

        return $this;
    }

    /**
     * Gets modified_attack_vector
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackVectorType|null
     */
    public function getModifiedAttackVector()
    {
        return $this->container['modified_attack_vector'];
    }

    /**
     * Sets modified_attack_vector
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackVectorType|null $modified_attack_vector modified_attack_vector
     *
     * @return self
     */
    public function setModifiedAttackVector($modified_attack_vector)
    {
        if (is_null($modified_attack_vector)) {
            throw new \InvalidArgumentException('non-nullable modified_attack_vector cannot be null');
        }
        $this->container['modified_attack_vector'] = $modified_attack_vector;

        return $this;
    }

    /**
     * Gets modified_attack_complexity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackComplexityType|null
     */
    public function getModifiedAttackComplexity()
    {
        return $this->container['modified_attack_complexity'];
    }

    /**
     * Sets modified_attack_complexity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedAttackComplexityType|null $modified_attack_complexity modified_attack_complexity
     *
     * @return self
     */
    public function setModifiedAttackComplexity($modified_attack_complexity)
    {
        if (is_null($modified_attack_complexity)) {
            throw new \InvalidArgumentException('non-nullable modified_attack_complexity cannot be null');
        }
        $this->container['modified_attack_complexity'] = $modified_attack_complexity;

        return $this;
    }

    /**
     * Gets modified_privileges_required
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedPrivilegesRequiredType|null
     */
    public function getModifiedPrivilegesRequired()
    {
        return $this->container['modified_privileges_required'];
    }

    /**
     * Sets modified_privileges_required
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedPrivilegesRequiredType|null $modified_privileges_required modified_privileges_required
     *
     * @return self
     */
    public function setModifiedPrivilegesRequired($modified_privileges_required)
    {
        if (is_null($modified_privileges_required)) {
            throw new \InvalidArgumentException('non-nullable modified_privileges_required cannot be null');
        }
        $this->container['modified_privileges_required'] = $modified_privileges_required;

        return $this;
    }

    /**
     * Gets modified_user_interaction
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedUserInteractionType|null
     */
    public function getModifiedUserInteraction()
    {
        return $this->container['modified_user_interaction'];
    }

    /**
     * Sets modified_user_interaction
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedUserInteractionType|null $modified_user_interaction modified_user_interaction
     *
     * @return self
     */
    public function setModifiedUserInteraction($modified_user_interaction)
    {
        if (is_null($modified_user_interaction)) {
            throw new \InvalidArgumentException('non-nullable modified_user_interaction cannot be null');
        }
        $this->container['modified_user_interaction'] = $modified_user_interaction;

        return $this;
    }

    /**
     * Gets modified_scope
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedScopeType|null
     */
    public function getModifiedScope()
    {
        return $this->container['modified_scope'];
    }

    /**
     * Sets modified_scope
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedScopeType|null $modified_scope modified_scope
     *
     * @return self
     */
    public function setModifiedScope($modified_scope)
    {
        if (is_null($modified_scope)) {
            throw new \InvalidArgumentException('non-nullable modified_scope cannot be null');
        }
        $this->container['modified_scope'] = $modified_scope;

        return $this;
    }

    /**
     * Gets modified_confidentiality_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null
     */
    public function getModifiedConfidentialityImpact()
    {
        return $this->container['modified_confidentiality_impact'];
    }

    /**
     * Sets modified_confidentiality_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null $modified_confidentiality_impact modified_confidentiality_impact
     *
     * @return self
     */
    public function setModifiedConfidentialityImpact($modified_confidentiality_impact)
    {
        if (is_null($modified_confidentiality_impact)) {
            throw new \InvalidArgumentException('non-nullable modified_confidentiality_impact cannot be null');
        }
        $this->container['modified_confidentiality_impact'] = $modified_confidentiality_impact;

        return $this;
    }

    /**
     * Gets modified_integrity_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null
     */
    public function getModifiedIntegrityImpact()
    {
        return $this->container['modified_integrity_impact'];
    }

    /**
     * Sets modified_integrity_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null $modified_integrity_impact modified_integrity_impact
     *
     * @return self
     */
    public function setModifiedIntegrityImpact($modified_integrity_impact)
    {
        if (is_null($modified_integrity_impact)) {
            throw new \InvalidArgumentException('non-nullable modified_integrity_impact cannot be null');
        }
        $this->container['modified_integrity_impact'] = $modified_integrity_impact;

        return $this;
    }

    /**
     * Gets modified_availability_impact
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null
     */
    public function getModifiedAvailabilityImpact()
    {
        return $this->container['modified_availability_impact'];
    }

    /**
     * Sets modified_availability_impact
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30ModifiedCiaType|null $modified_availability_impact modified_availability_impact
     *
     * @return self
     */
    public function setModifiedAvailabilityImpact($modified_availability_impact)
    {
        if (is_null($modified_availability_impact)) {
            throw new \InvalidArgumentException('non-nullable modified_availability_impact cannot be null');
        }
        $this->container['modified_availability_impact'] = $modified_availability_impact;

        return $this;
    }

    /**
     * Gets environmental_score
     *
     * @return float|null
     */
    public function getEnvironmentalScore()
    {
        return $this->container['environmental_score'];
    }

    /**
     * Sets environmental_score
     *
     * @param float|null $environmental_score environmental_score
     *
     * @return self
     */
    public function setEnvironmentalScore($environmental_score)
    {
        if (is_null($environmental_score)) {
            throw new \InvalidArgumentException('non-nullable environmental_score cannot be null');
        }

        if (($environmental_score > 10.0)) {
            throw new \InvalidArgumentException('invalid value for $environmental_score when calling CommonModelsCvssV30CveCvssDataModel., must be smaller than or equal to 10.0.');
        }
        if (($environmental_score < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $environmental_score when calling CommonModelsCvssV30CveCvssDataModel., must be bigger than or equal to 0.0.');
        }

        $this->container['environmental_score'] = $environmental_score;

        return $this;
    }

    /**
     * Gets environmental_severity
     *
     * @return \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType|null
     */
    public function getEnvironmentalSeverity()
    {
        return $this->container['environmental_severity'];
    }

    /**
     * Sets environmental_severity
     *
     * @param \Msn\Apis\FastCVE\Model\CommonModelsCvssV30SeverityType|null $environmental_severity environmental_severity
     *
     * @return self
     */
    public function setEnvironmentalSeverity($environmental_severity)
    {
        if (is_null($environmental_severity)) {
            throw new \InvalidArgumentException('non-nullable environmental_severity cannot be null');
        }
        $this->container['environmental_severity'] = $environmental_severity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


