<?php
/**
 * CommonModelsCvssV30RemediationLevelType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Msn\Apis\FastCVE\Model;
use \Msn\Apis\FastCVE\ObjectSerializer;

/**
 * CommonModelsCvssV30RemediationLevelType Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommonModelsCvssV30RemediationLevelType
{
    /**
     * Possible values of this enum
     */
    public const OFFICIAL_FIX = 'OFFICIAL_FIX';

    public const TEMPORARY_FIX = 'TEMPORARY_FIX';

    public const WORKAROUND = 'WORKAROUND';

    public const UNAVAILABLE = 'UNAVAILABLE';

    public const NOT_DEFINED = 'NOT_DEFINED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OFFICIAL_FIX,
            self::TEMPORARY_FIX,
            self::WORKAROUND,
            self::UNAVAILABLE,
            self::NOT_DEFINED
        ];
    }
}


