<?php
/**
 * CpeMatch
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Msn\Apis\FastCVE\Model;

use \ArrayAccess;
use \Msn\Apis\FastCVE\ObjectSerializer;

/**
 * CpeMatch Class Doc Comment
 *
 * @category Class
 * @description CPE match string or range
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CpeMatch implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CpeMatch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'vulnerable' => 'bool',
        'criteria' => 'string',
        'match_criteria_id' => 'string',
        'version_start_excluding' => 'string',
        'version_start_including' => 'string',
        'version_end_excluding' => 'string',
        'version_end_including' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'vulnerable' => null,
        'criteria' => null,
        'match_criteria_id' => 'uuid',
        'version_start_excluding' => null,
        'version_start_including' => null,
        'version_end_excluding' => null,
        'version_end_including' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'vulnerable' => false,
		'criteria' => false,
		'match_criteria_id' => false,
		'version_start_excluding' => false,
		'version_start_including' => false,
		'version_end_excluding' => false,
		'version_end_including' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'vulnerable' => 'vulnerable',
        'criteria' => 'criteria',
        'match_criteria_id' => 'matchCriteriaId',
        'version_start_excluding' => 'versionStartExcluding',
        'version_start_including' => 'versionStartIncluding',
        'version_end_excluding' => 'versionEndExcluding',
        'version_end_including' => 'versionEndIncluding'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'vulnerable' => 'setVulnerable',
        'criteria' => 'setCriteria',
        'match_criteria_id' => 'setMatchCriteriaId',
        'version_start_excluding' => 'setVersionStartExcluding',
        'version_start_including' => 'setVersionStartIncluding',
        'version_end_excluding' => 'setVersionEndExcluding',
        'version_end_including' => 'setVersionEndIncluding'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'vulnerable' => 'getVulnerable',
        'criteria' => 'getCriteria',
        'match_criteria_id' => 'getMatchCriteriaId',
        'version_start_excluding' => 'getVersionStartExcluding',
        'version_start_including' => 'getVersionStartIncluding',
        'version_end_excluding' => 'getVersionEndExcluding',
        'version_end_including' => 'getVersionEndIncluding'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('vulnerable', $data ?? [], null);
        $this->setIfExists('criteria', $data ?? [], null);
        $this->setIfExists('match_criteria_id', $data ?? [], null);
        $this->setIfExists('version_start_excluding', $data ?? [], null);
        $this->setIfExists('version_start_including', $data ?? [], null);
        $this->setIfExists('version_end_excluding', $data ?? [], null);
        $this->setIfExists('version_end_including', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['vulnerable'] === null) {
            $invalidProperties[] = "'vulnerable' can't be null";
        }
        if ($this->container['criteria'] === null) {
            $invalidProperties[] = "'criteria' can't be null";
        }
        if ($this->container['match_criteria_id'] === null) {
            $invalidProperties[] = "'match_criteria_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets vulnerable
     *
     * @return bool
     */
    public function getVulnerable()
    {
        return $this->container['vulnerable'];
    }

    /**
     * Sets vulnerable
     *
     * @param bool $vulnerable vulnerable
     *
     * @return self
     */
    public function setVulnerable($vulnerable)
    {
        if (is_null($vulnerable)) {
            throw new \InvalidArgumentException('non-nullable vulnerable cannot be null');
        }
        $this->container['vulnerable'] = $vulnerable;

        return $this;
    }

    /**
     * Gets criteria
     *
     * @return string
     */
    public function getCriteria()
    {
        return $this->container['criteria'];
    }

    /**
     * Sets criteria
     *
     * @param string $criteria criteria
     *
     * @return self
     */
    public function setCriteria($criteria)
    {
        if (is_null($criteria)) {
            throw new \InvalidArgumentException('non-nullable criteria cannot be null');
        }
        $this->container['criteria'] = $criteria;

        return $this;
    }

    /**
     * Gets match_criteria_id
     *
     * @return string
     */
    public function getMatchCriteriaId()
    {
        return $this->container['match_criteria_id'];
    }

    /**
     * Sets match_criteria_id
     *
     * @param string $match_criteria_id match_criteria_id
     *
     * @return self
     */
    public function setMatchCriteriaId($match_criteria_id)
    {
        if (is_null($match_criteria_id)) {
            throw new \InvalidArgumentException('non-nullable match_criteria_id cannot be null');
        }
        $this->container['match_criteria_id'] = $match_criteria_id;

        return $this;
    }

    /**
     * Gets version_start_excluding
     *
     * @return string|null
     */
    public function getVersionStartExcluding()
    {
        return $this->container['version_start_excluding'];
    }

    /**
     * Sets version_start_excluding
     *
     * @param string|null $version_start_excluding version_start_excluding
     *
     * @return self
     */
    public function setVersionStartExcluding($version_start_excluding)
    {
        if (is_null($version_start_excluding)) {
            throw new \InvalidArgumentException('non-nullable version_start_excluding cannot be null');
        }
        $this->container['version_start_excluding'] = $version_start_excluding;

        return $this;
    }

    /**
     * Gets version_start_including
     *
     * @return string|null
     */
    public function getVersionStartIncluding()
    {
        return $this->container['version_start_including'];
    }

    /**
     * Sets version_start_including
     *
     * @param string|null $version_start_including version_start_including
     *
     * @return self
     */
    public function setVersionStartIncluding($version_start_including)
    {
        if (is_null($version_start_including)) {
            throw new \InvalidArgumentException('non-nullable version_start_including cannot be null');
        }
        $this->container['version_start_including'] = $version_start_including;

        return $this;
    }

    /**
     * Gets version_end_excluding
     *
     * @return string|null
     */
    public function getVersionEndExcluding()
    {
        return $this->container['version_end_excluding'];
    }

    /**
     * Sets version_end_excluding
     *
     * @param string|null $version_end_excluding version_end_excluding
     *
     * @return self
     */
    public function setVersionEndExcluding($version_end_excluding)
    {
        if (is_null($version_end_excluding)) {
            throw new \InvalidArgumentException('non-nullable version_end_excluding cannot be null');
        }
        $this->container['version_end_excluding'] = $version_end_excluding;

        return $this;
    }

    /**
     * Gets version_end_including
     *
     * @return string|null
     */
    public function getVersionEndIncluding()
    {
        return $this->container['version_end_including'];
    }

    /**
     * Sets version_end_including
     *
     * @param string|null $version_end_including version_end_including
     *
     * @return self
     */
    public function setVersionEndIncluding($version_end_including)
    {
        if (is_null($version_end_including)) {
            throw new \InvalidArgumentException('non-nullable version_end_including cannot be null');
        }
        $this->container['version_end_including'] = $version_end_including;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


