<?php
/**
 * Metrics
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Msn\Apis\FastCVE\Model;

use \ArrayAccess;
use \Msn\Apis\FastCVE\ObjectSerializer;

/**
 * Metrics Class Doc Comment
 *
 * @category Class
 * @description Metric scores for a vulnerability as found on NVD.
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Metrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Metrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cvss_metric_v31' => '\Msn\Apis\FastCVE\Model\CvssV31[]',
        'cvss_metric_v30' => '\Msn\Apis\FastCVE\Model\CvssV30[]',
        'cvss_metric_v2' => '\Msn\Apis\FastCVE\Model\CvssV2[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cvss_metric_v31' => null,
        'cvss_metric_v30' => null,
        'cvss_metric_v2' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cvss_metric_v31' => false,
		'cvss_metric_v30' => false,
		'cvss_metric_v2' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cvss_metric_v31' => 'cvssMetricV31',
        'cvss_metric_v30' => 'cvssMetricV30',
        'cvss_metric_v2' => 'cvssMetricV2'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cvss_metric_v31' => 'setCvssMetricV31',
        'cvss_metric_v30' => 'setCvssMetricV30',
        'cvss_metric_v2' => 'setCvssMetricV2'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cvss_metric_v31' => 'getCvssMetricV31',
        'cvss_metric_v30' => 'getCvssMetricV30',
        'cvss_metric_v2' => 'getCvssMetricV2'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('cvss_metric_v31', $data ?? [], null);
        $this->setIfExists('cvss_metric_v30', $data ?? [], null);
        $this->setIfExists('cvss_metric_v2', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cvss_metric_v31
     *
     * @return \Msn\Apis\FastCVE\Model\CvssV31[]|null
     */
    public function getCvssMetricV31()
    {
        return $this->container['cvss_metric_v31'];
    }

    /**
     * Sets cvss_metric_v31
     *
     * @param \Msn\Apis\FastCVE\Model\CvssV31[]|null $cvss_metric_v31 CVSS V3.1 score.
     *
     * @return self
     */
    public function setCvssMetricV31($cvss_metric_v31)
    {
        if (is_null($cvss_metric_v31)) {
            throw new \InvalidArgumentException('non-nullable cvss_metric_v31 cannot be null');
        }
        $this->container['cvss_metric_v31'] = $cvss_metric_v31;

        return $this;
    }

    /**
     * Gets cvss_metric_v30
     *
     * @return \Msn\Apis\FastCVE\Model\CvssV30[]|null
     */
    public function getCvssMetricV30()
    {
        return $this->container['cvss_metric_v30'];
    }

    /**
     * Sets cvss_metric_v30
     *
     * @param \Msn\Apis\FastCVE\Model\CvssV30[]|null $cvss_metric_v30 CVSS V3.0 score.
     *
     * @return self
     */
    public function setCvssMetricV30($cvss_metric_v30)
    {
        if (is_null($cvss_metric_v30)) {
            throw new \InvalidArgumentException('non-nullable cvss_metric_v30 cannot be null');
        }
        $this->container['cvss_metric_v30'] = $cvss_metric_v30;

        return $this;
    }

    /**
     * Gets cvss_metric_v2
     *
     * @return \Msn\Apis\FastCVE\Model\CvssV2[]|null
     */
    public function getCvssMetricV2()
    {
        return $this->container['cvss_metric_v2'];
    }

    /**
     * Sets cvss_metric_v2
     *
     * @param \Msn\Apis\FastCVE\Model\CvssV2[]|null $cvss_metric_v2 CVSS V2.0 score.
     *
     * @return self
     */
    public function setCvssMetricV2($cvss_metric_v2)
    {
        if (is_null($cvss_metric_v2)) {
            throw new \InvalidArgumentException('non-nullable cvss_metric_v2 cannot be null');
        }
        $this->container['cvss_metric_v2'] = $cvss_metric_v2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


