<?php
/**
 * CpeMatchTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Msn\Apis\FastCVE\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CpeMatchTest Class Doc Comment
 *
 * @category    Class
 * @description CPE match string or range
 * @package     Msn\Apis\FastCVE
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CpeMatchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CpeMatch"
     */
    public function testCpeMatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vulnerable"
     */
    public function testPropertyVulnerable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "criteria"
     */
    public function testPropertyCriteria()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "match_criteria_id"
     */
    public function testPropertyMatchCriteriaId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version_start_excluding"
     */
    public function testPropertyVersionStartExcluding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version_start_including"
     */
    public function testPropertyVersionStartIncluding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version_end_excluding"
     */
    public function testPropertyVersionEndExcluding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version_end_including"
     */
    public function testPropertyVersionEndIncluding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
