<?php
/**
 * SearchApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastCVE
 *
 * fast, rich and API-based search for CVE and more (CPE, CWE, CAPEC)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Msn\Apis\FastCVE\Test\Api;

use \Msn\Apis\FastCVE\Configuration;
use \Msn\Apis\FastCVE\ApiException;
use \Msn\Apis\FastCVE\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Msn\Apis\FastCVE
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for searchCAPECApiSearchCapecGet
     *
     * Search Capec.
     *
     */
    public function testSearchCAPECApiSearchCapecGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCPEApiSearchCpeGet
     *
     * Search Cpe.
     *
     */
    public function testSearchCPEApiSearchCpeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCVEApiSearchCveGet
     *
     * Search Cve.
     *
     */
    public function testSearchCVEApiSearchCveGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCWEApiSearchCweGet
     *
     * Search Cwe.
     *
     */
    public function testSearchCWEApiSearchCweGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
